on:
  push:
    branches:
      - prodDev
name: Auto-Prod Deploy
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USER }}
          server: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          local_path: './*'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.PASS }}
